#!/bin/bash
##
## Validate FV private key.  Enter as parameter in JAMF script and scope to 1 computer
##

testKey="$4"

fdesetup validaterecovery -inputplist <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>Password</key>
<string>$testKey</string>
</dict>
</plist>
EOF
